### ISSUE TITLE
Adding Github mods causes SendFailure

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#37]
Linux v2.0.0.10

When I try to add ``https://github.com/TriggerAu/KerbalAlarmClock`` or ``https://github.com/Starwaster/DeadlyReentry`` I get the following error:

```
[7] Info    : Url detected starting download...
[1] Error   : Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
Exception: System.Net.WebException
Message: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
StackTrace:
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0
  at HtmlAgilityPack.HtmlWeb.Get (System.Uri uri, System.String method, System.String path, HtmlAgilityPack.HtmlDocument doc, IWebProxy proxy, ICredentials creds) [0x00000] in <filename unknown>:0
```

**Comment by EoD** [comment]
Yes, it's a Linux only bug. I doubt it's a bug in mono though.

**Comment by MacTee** [comment]
Should be the solution (from http://www.mono-project.com/docs/faq/security/):
"...That’s probably because you do not trust the site you are connecting to. Note that a default installation of Mono doesn’t trust anyone!..."

Please try this:
"...
- Use the mozroots.exe tool (included in Mono 1.1.10 and later) to download and install all Mozilla’s root certificates (i.e. the ones used in FireFox and other Mozilla’s softwares). It’s easier than finding a specific root but it’s also less granular to make a decision about which one(s) you install or not.
..."

**Comment by EoD** [comment]
I did a ``mozroots --sync --import``:
```
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Importing certificates into user store...
138 new root certificates were added to your trust store.
Import process completed.
```

This fixed the issue. Can you automate this in your program such that I don't have to install those certs globally?

**Comment by MacTee** [comment]
I know I should, but I have to figure out how first ;)
