### ISSUE TITLE
Extracting many files is really slow

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#54]
Linux v2.0.0.11

When I install [Crowd Sourced Science](https://github.com/DuoDex/CrowdSourcedScience/releases) the extraction process takes about 1-3 seconds **per** cfg file. Those cfg files are a few kilobytes in size. That sounds really slow for extracting a few kilobytes.

Is this a design flaw (hence an enhancement) or a bug in the code?

If this is hard to fix, is it possible to add a "Cancel" button which stops the extraction? This way you could at least extract it manually.

**Comment by MacTee** [comment]
The problem here is the aproch i use for extracting.

I don't know:
- if the user has changed destination paths
- if i should extract all of the mod (is every mod file checked)

With this in mind i can't just dump the archive, or parts of it, somewhere.

So i cycle through all files of a mod and extract them one by one. That means that for every extracted file i have to look through the Archive to find the file to extract. That takes some time on big archives (big ~ many files).

I thought about to extract the complete archive in a temp folder and then copy the wanted files. But if you just want to use some parts of a big mod (big ~ size) like me you have to wait longer ...

A "Cancel" option might be the solution here, but this is complicated too:
What should i do with the already installed content? 
Should i remove all files installed during the canceld extract session? 
Or just those related to the mod which was extracted during the click on cancel?
That are just some "install related" questions/problems to handle, what about you have install and uninstall operations ...

It sounds like a easy feature but there is more behind it.
Its still a valid feature request, i'll note it to my todo list, but it won't be implemented soon.

**Comment by EoD** [comment]
Why don't you dump the archive in a temporary folder (like "AppData\Roaming\Temp" in Windows or "/tmp" in linux) and decide **afterwards** if what files you need to put where?

**Comment by MacTee** [comment]
A few reasons:
- As mentioned above if you just use a few parts from a large mod (like me) it would be slower.
- i don't want to write/read to/from to many different folders.
- i would have to write a "temp file handler" to reference/track file-archive relations, clean up, etc.

But i noted it to the todo list for later ;)
