### ISSUE TITLE
FAR/NEAR share the same git repository

### ISSUE THREAD

**Issue by EoD** [MacTee/KSP-Mod-Admin-aOS#56]
There is a problem when you try to install NEAR via KSPMA. Both FAR and NEAR share the [same github repository](
https://github.com/ferram4/Ferram-Aerospace-Research/releases) and are only distinguished by the name of the tag.

Is it possible to work around that issue?

EDIT: I found a trivial solution: use [kerbalstuff](https://kerbalstuff.com/mod/54/Neophyte%27s%20Elementary%20Aerodynamics%20Replacement) instead of github. Nevertheless this issue might also cause an FAR->NEAR and NEAR->FAR update unintentionally if the github repo is used.

**Comment by Gribbleshnibit8** [comment]
Ideally everyone would use kerbalstuff for mods that support it, and more mods need to use kerbalstuff, since it's the best provided for site and the only one with an actual API.

I actually considered a solution for github sites that just listed all available downloads and let the user pick, but that doesn't help for updates. I can easily get tags and stuff from the page, but I'd have to add a field  to store the tag in association with that mod to ensure proper updating. The problem with that is everyone might use a different tag schema to differentiate.

If anyone can propose a solution, I will try my best to implement it, but I can't think of anything that would work ideally through updates without being tied heavily to single repository instances.

**Comment by MacTee** [comment]
I think we can't do much about that "problem".
As long as the mod is distributed through some other channes, like here with KerbalStuff, there is a valid "workaround". 
Somt things we can't fix without inventing some fancy AI ;)
